version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snipbox_db
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"